version: '3'

vars:
  PAPER_DIR: paper
  OUTPUT_DIR: output
  PAPER_NAME: dsp4d-paper

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # === Setup ===
  setup:
    desc: Install required dependencies (pandoc, basictex)
    cmds:
      - echo "Installing pandoc..."
      - brew install pandoc
      - echo "Installing BasicTeX (minimal LaTeX distribution)..."
      - brew install --cask basictex
      - echo ""
      - echo "After installation, run 'task setup-latex' to install required LaTeX packages"
    status:
      - which pandoc

  setup-latex:
    desc: Install required LaTeX packages
    vars:
      TLMGR: /Library/TeX/texbin/tlmgr
    cmds:
      - sudo {{.TLMGR}} update --self
      - sudo {{.TLMGR}} install collection-fontsrecommended
      - sudo {{.TLMGR}} install bookmark xcolor mdwtools etoolbox
      - sudo {{.TLMGR}} install infwarerr kvoptions pdftexcmds
      - sudo {{.TLMGR}} install hycolor letltxmacro auxhook
      - sudo {{.TLMGR}} install intcalc rerunfilecheck
      - echo "LaTeX packages installed successfully"

  # === Build ===
  build:
    desc: Build PDF from paper
    deps: [ensure-output-dir]
    cmds:
      - pandoc --defaults={{.PAPER_DIR}}/defaults.yaml {{.PAPER_DIR}}/paper.md -o {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.pdf
      - echo "PDF created {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.pdf"

  build-draft:
    desc: Build PDF without bibliography processing (faster)
    deps: [ensure-output-dir]
    cmds:
      - pandoc --defaults={{.PAPER_DIR}}/defaults.yaml --citeproc=false {{.PAPER_DIR}}/paper.md -o {{.OUTPUT_DIR}}/{{.PAPER_NAME}}-draft.pdf
      - echo "Draft PDF created {{.OUTPUT_DIR}}/{{.PAPER_NAME}}-draft.pdf"

  build-word:
    desc: Build Word document (for sharing with non-technical reviewers)
    deps: [ensure-output-dir]
    cmds:
      - pandoc --defaults={{.PAPER_DIR}}/defaults.yaml {{.PAPER_DIR}}/paper.md -o {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.docx
      - echo "Word document created {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.docx"

  build-html:
    desc: Build HTML version
    deps: [ensure-output-dir]
    cmds:
      - pandoc --defaults={{.PAPER_DIR}}/defaults.yaml --standalone --toc {{.PAPER_DIR}}/paper.md -o {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.html
      - echo "HTML created {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.html"

  # === Development ===
  watch:
    desc: Watch for changes and rebuild PDF
    cmds:
      - echo "Watching for changes in {{.PAPER_DIR}}/... Press Ctrl+C to stop"
      - fswatch -o {{.PAPER_DIR}}/*.md {{.PAPER_DIR}}/*.yaml {{.PAPER_DIR}}/*.bib | xargs -n1 -I{} task build

  open:
    desc: Open the PDF
    cmds:
      - open {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.pdf

  # === Utilities ===
  clean:
    desc: Remove generated files
    cmds:
      - rm -rf {{.OUTPUT_DIR}}
      - echo "Cleaned output directory"

  ensure-output-dir:
    internal: true
    cmds:
      - mkdir -p {{.OUTPUT_DIR}}
    status:
      - test -d {{.OUTPUT_DIR}}
