version: '3'

vars:
  PAPER_DIR: .
  OUTPUT_DIR: output
  PAPER_NAME: dsp4d-paper

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  # === Setup (platform-specific) ===
  setup:
    desc: Install required dependencies (pandoc, LaTeX)
    cmds:
      - task: setup-{{OS}}

  setup-darwin:
    internal: true
    cmds:
      - echo "Installing pandoc..."
      - brew install pandoc
      - echo "Installing BasicTeX..."
      - brew install --cask basictex
      - echo ""
      - echo "=========================================="
      - echo "IMPORTANT - BasicTeX has been installed!"
      - echo "You MUST restart your terminal, then run:"
      - echo "  cd paper && task setup-latex"
      - echo "=========================================="

  setup-linux:
    internal: true
    cmds:
      - echo "Installing dependencies..."
      - sudo apt-get update
      - sudo apt-get install -y wget texlive-latex-base texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-lang-german
      - echo "Installing Pandoc 3.1.11.1..."
      - wget -q https://github.com/jgm/pandoc/releases/download/3.1.11.1/pandoc-3.1.11.1-1-amd64.deb
      - sudo dpkg -i pandoc-3.1.11.1-1-amd64.deb
      - rm pandoc-3.1.11.1-1-amd64.deb
      - echo "Setup complete"
    status:
      - pandoc --version | grep "3.1.11.1"

  setup-windows:
    internal: true
    cmds:
      - echo "Installing pandoc and MiKTeX via Chocolatey..."
      - choco install pandoc miktex -y
      - echo ""
      - echo "Restart your terminal, then run 'task setup-latex'"
    status:
      - where pandoc

  setup-latex:
    desc: Install required LaTeX packages
    cmds:
      - task: setup-latex-{{OS}}

  setup-latex-darwin:
    internal: true
    preconditions:
      - sh: test -d /Library/TeX/texbin || test -d /usr/local/texlive/*/bin/*
        msg: "BasicTeX not found. Please run 'task setup' first and restart your terminal."
    cmds:
      - |
        # Find tlmgr in common locations
        if [ -x "/Library/TeX/texbin/tlmgr" ]; then
          TLMGR="/Library/TeX/texbin/tlmgr"
        elif [ -x "/usr/local/texlive/2024/bin/universal-darwin/tlmgr" ]; then
          TLMGR="/usr/local/texlive/2024/bin/universal-darwin/tlmgr"
        elif [ -x "/usr/local/texlive/2023/bin/universal-darwin/tlmgr" ]; then
          TLMGR="/usr/local/texlive/2023/bin/universal-darwin/tlmgr"
        else
          TLMGR=$(which tlmgr 2>/dev/null)
        fi
        
        if [ -z "$TLMGR" ] || [ ! -x "$TLMGR" ]; then
          echo "Error: tlmgr not found. Please ensure BasicTeX is installed."
          exit 1
        fi
        
        echo "Found tlmgr at: $TLMGR"
        sudo "$TLMGR" update --self
        sudo "$TLMGR" install collection-fontsrecommended bookmark xcolor mdwtools etoolbox infwarerr kvoptions pdftexcmds hycolor letltxmacro auxhook intcalc rerunfilecheck framed
        echo "LaTeX packages installed"

  setup-latex-linux:
    internal: true
    cmds:
      - echo "LaTeX packages already included in texlive-latex-extra"

  setup-latex-windows:
    internal: true
    cmds:
      - echo "MiKTeX will auto-install packages on first use"

  # === Build (cross-platform) ===
  build:
    desc: Build PDF from paper (BFH thesis template)
    deps: [ensure-output-dir]
    cmds:
      - >
        PATH="/Library/TeX/texbin:$PATH"
        pandoc --defaults={{.PAPER_DIR}}/defaults.yaml
        -o {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.pdf
      - echo "PDF created {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.pdf"

  build-draft:
    desc: Build PDF without bibliography processing (faster)
    deps: [ensure-output-dir]
    cmds:
      - >
        PATH="/Library/TeX/texbin:$PATH"
        pandoc --defaults={{.PAPER_DIR}}/defaults.yaml --citeproc=false
        -o {{.OUTPUT_DIR}}/{{.PAPER_NAME}}-draft.pdf
      - echo "Draft PDF created {{.OUTPUT_DIR}}/{{.PAPER_NAME}}-draft.pdf"

  build-word:
    desc: Build Word document with custom reference template
    deps: [ensure-output-dir]
    cmds:
      - >
        pandoc --defaults={{.PAPER_DIR}}/defaults.yaml
        --to docx
        --reference-doc={{.PAPER_DIR}}/reference-styles.docx
        -o {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.docx
      - echo "Word document created {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.docx using template"

  build-html:
    desc: Build HTML version
    deps: [ensure-output-dir]
    cmds:
      - >
        pandoc --defaults={{.PAPER_DIR}}/defaults.yaml
        --to html
        --standalone --toc
        -o {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.html
      - echo "HTML created {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.html"

  # === Development ===
  watch:
    desc: Watch for changes and rebuild PDF
    cmds:
      - task: watch-{{OS}}

  watch-darwin:
    internal: true
    cmds:
      - echo "Watching {{.PAPER_DIR}}/chapters/ recursively... (requires 'brew install fswatch')"
      - fswatch -r -e ".*" -i "\\.md$" -i "\\.yaml$" -i "\\.bib$" {{.PAPER_DIR}}/chapters {{.PAPER_DIR}}/defaults.yaml {{.PAPER_DIR}}/references.bib | xargs -n1 -I{} task build

  watch-linux:
    internal: true
    cmds:
      - echo "Watching {{.PAPER_DIR}}/chapters/ recursively... (requires 'apt install inotify-tools')"
      - while inotifywait -r -e modify,create,delete --include '\.(md|yaml|bib)$' {{.PAPER_DIR}}/chapters {{.PAPER_DIR}}; do task build; done

  watch-windows:
    internal: true
    cmds:
      - echo "File watching not directly supported on Windows."
      - echo "Consider using VS Code with 'Run on Save' extension, or run 'task build' manually."

  open:
    desc: Open the PDF
    cmds:
      - task: open-{{OS}}

  open-darwin:
    internal: true
    cmds:
      - open {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.pdf

  open-linux:
    internal: true
    cmds:
      - xdg-open {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.pdf

  open-windows:
    internal: true
    cmds:
      - start {{.OUTPUT_DIR}}/{{.PAPER_NAME}}.pdf

  # === Utilities ===
  clean:
    desc: Remove generated files
    cmds:
      - task: clean-{{OS}}

  clean-darwin:
    internal: true
    cmds:
      - rm -rf {{.OUTPUT_DIR}}
      - echo "Cleaned output directory"

  clean-linux:
    internal: true
    cmds:
      - rm -rf {{.OUTPUT_DIR}}
      - echo "Cleaned output directory"

  clean-windows:
    internal: true
    cmds:
      - cmd /c "if exist {{.OUTPUT_DIR}} rmdir /s /q {{.OUTPUT_DIR}}"
      - echo "Cleaned output directory"

  ensure-output-dir:
    internal: true
    cmds:
      - task: ensure-output-dir-{{OS}}

  ensure-output-dir-darwin:
    internal: true
    cmds:
      - mkdir -p {{.OUTPUT_DIR}}
    status:
      - test -d {{.OUTPUT_DIR}}

  ensure-output-dir-linux:
    internal: true
    cmds:
      - mkdir -p {{.OUTPUT_DIR}}
    status:
      - test -d {{.OUTPUT_DIR}}

  ensure-output-dir-windows:
    internal: true
    cmds:
      - cmd /c "if not exist {{.OUTPUT_DIR}} mkdir {{.OUTPUT_DIR}}"
    status:
      - cmd /c "if exist {{.OUTPUT_DIR}} exit 0"
